image: docker:24.0-dind

stages:
    - build-webapp
    - build-image
    - test
    - deploy
    - renovate

build-angular:
    stage: build-webapp
    image: node:20.3
    script:
        - npm ci --cache .npm --prefer-offline
        - npm run build
    artifacts:
        paths:
            - dist/
    cache:
        key: npm
        paths:
            - .npm/

build-image:
    stage: build-image
    needs: ["build-angular"]
    dependencies:
        - build-angular

    image: registry.green-rabbit.net:5000/kimata/ubuntu-docker-build:d386d462

    variables:
        BUILDER: arm_builder

    script:
        - export GIT_SSL_NO_VERIFY=1
        - git clone https://gitlab.green-rabbit.net/kimata/hems_config.git
        - mv hems_config/rasp-water.yaml config.yaml
        - git config --global --add safe.directory ${PWD}

        - docker buildx create --name ${BUILDER} --config script/buildkitd.toml --use
        - docker buildx use ${BUILDER}
        - docker buildx build --platform linux/amd64,linux/arm64/v8
          --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:cache
          --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:cache
          --push --tag ${CI_REGISTRY_IMAGE} .
        # - docker buildx stop ${BUILDER}

# NOTE: Playwright を使うようになったので削除
# test-cypress:
#     stage: test
#     image: cypress/included:12.13.0
#     script:
#         - npm ci --cache .npm --prefer-offline
#         - npx start-server-and-test 'ng serve' http-get://localhost:4200/ 'npx cypress run'
#     cache:
#         key: npm
#         paths:
#             - .npm/

test-flask:
    stage: test

    needs: ["build-angular"]
    dependencies:
        - build-angular

    image: registry.green-rabbit.net:5000/kimata/local_playwright:230623A
    script:
        - export GIT_SSL_NO_VERIFY=1
        - git clone https://gitlab.green-rabbit.net/kimata/hems_config.git
        - mv hems_config/rasp-water.yaml config.yaml
        - apt-get install -y python3-flask python3-flask-cors python3-yaml
          python3-schedule python3-fluent-logger python3-coloredlogs python3-docopt
          python3-psutil python3-pip
        - pip install -r requirements.txt
        # NOTE: 単純に起動することだけをチェック
        - python3 ./flask/app/app.py -D 2>&1 | tee flask_log.txt &
        - sleep 10
    artifacts:
        when: always
        paths:
            - flask_log.txt

test-playwright:
    stage: test
    needs: ["build-angular", "test-flask"]
    dependencies:
        - test-flask

    image: registry.green-rabbit.net:5000/kimata/local_playwright:230623A
    script:
        - export GIT_SSL_NO_VERIFY=1
        - git clone https://gitlab.green-rabbit.net/kimata/hems_config.git
        - mv hems_config/rasp-water.yaml config.yaml
        - apt-get install -y python3-flask python3-flask-cors python3-yaml
          python3-schedule python3-fluent-logger python3-coloredlogs python3-docopt
          python3-psutil python3-pip
        - pip install -r requirements.txt
        - python3 ./flask/app/app.py -D > flask_log.txt 2>&1 &
        - python3 -m pytest test/test_basic.py
    artifacts:
        when: always
        paths:
            - flask_log.txt
            - test/evidence/**

test-playwright-docker:
    stage: test
    needs: ["build-image"]

    image: registry.green-rabbit.net:5000/kimata/local_playwright:230623A

    script:
        # NOTE: テストに失敗するとテスト用のコンテナが残るので削除する
        - docker ps  --filter "label=job=${CI_JOB_NAME}" | grep hours | cut -d " " -f1 | while read id; do docker stop -t 5 $id; done || true

        - docker pull ${CI_REGISTRY_IMAGE}
        - docker run --rm --detach=true --tty=true --name ${CI_JOB_NAME}-${CI_JOB_ID} --label job=${CI_JOB_NAME} ${CI_REGISTRY_IMAGE} ./flask/app/app.py -D
        - python3 -m pytest test/test_basic.py --host $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${CI_JOB_NAME}-${CI_JOB_ID})
        - docker logs ${CI_JOB_NAME}-${CI_JOB_ID} > flask_log.txt
        - docker stop ${CI_JOB_NAME}-${CI_JOB_ID}
    artifacts:
        when: always
        paths:
            - flask_log.txt
            - test/evidence/**

test-playwright-docker-demo:
    stage: test
    needs: ["build-image"]

    image: registry.green-rabbit.net:5000/kimata/local_playwright:230623A

    script:
        # NOTE: テストに失敗するとテスト用のコンテナが残るので削除する
        - docker ps  --filter "label=job=${CI_JOB_NAME}" | grep hours | cut -d " " -f1 | while read id; do docker stop -t 5 $id; done || true

        - docker stop ${CI_JOB_NAME} || true
        - docker pull ${CI_REGISTRY_IMAGE}
        - docker run --rm --detach=true --tty=true --name ${CI_JOB_NAME}-${CI_JOB_ID} --label job=${CI_JOB_NAME} ${CI_REGISTRY_IMAGE} ./flask/app/app.py -D -c config.example.yaml
        - python3 -m pytest test/test_basic.py --host $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${CI_JOB_NAME}-${CI_JOB_ID})
        - docker logs ${CI_JOB_NAME}-${CI_JOB_ID} > flask_log.txt
        - docker stop ${CI_JOB_NAME}-${CI_JOB_ID}
    artifacts:
        when: always
        paths:
            - flask_log.txt
            - test/evidence/**

test-healthz-docker:
    stage: test
    needs: ["build-image"]

    script:
        # NOTE: テストに失敗するとテスト用のコンテナが残るので削除する
        - docker ps  --filter "label=job=${CI_JOB_NAME}" | grep hours | cut -d " " -f1 | while read id; do docker stop -t 5 $id; done || true

        - docker pull ${CI_REGISTRY_IMAGE}
        - docker run --rm --detach=true --tty=true --name ${CI_JOB_NAME}-${CI_JOB_ID} --label job=${CI_JOB_NAME} ${CI_REGISTRY_IMAGE} ./flask/app/app.py -D

        - sleep 10
        - docker exec ${CI_JOB_NAME}-${CI_JOB_ID} ./flask/src/healthz.py

        - docker logs ${CI_JOB_NAME}-${CI_JOB_ID} > flask_log.txt
        - docker stop ${CI_JOB_NAME}-${CI_JOB_ID}
    artifacts:
        when: always
        paths:
            - flask_log.txt

deploy-webapp:
    stage: deploy
    needs: ["test-playwright-docker", "test-healthz-docker"]

    image:
        name: bitnami/kubectl:latest
        entrypoint: [""]
    script:
        - kubectl config get-contexts
        - kubectl config use-context kimata/rasp-water:pod-rollout
        - kubectl --insecure-skip-tls-verify=true rollout restart -n hems deployment rasp-water
    rules:
        # NOTE: 自動実行ではデプロイしない
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - changes:
              - flask/**/*
              - src/**/*

deploy-webapp-demo:
    stage: deploy
    needs: ["test-playwright-docker-demo", "test-healthz-docker"]

    image:
        name: bitnami/kubectl:latest
        entrypoint: [""]
    script:
        - kubectl config get-contexts
        - kubectl config use-context kimata/rasp-water:pod-rollout
        - kubectl --insecure-skip-tls-verify=true rollout restart -n hems deployment rasp-water-demo
    rules:
        # NOTE: 自動実行ではデプロイしない
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - changes:
              - flask/**/*
              - src/**/*

renovate:
    stage: renovate
    image:
        name: registry.green-rabbit.net:5000/kimata/local_renovate:35

        entrypoint: [""]
    script:
        - renovate --platform gitlab --token ${RENOVATE_TOKEN} --endpoint ${CI_SERVER_URL}/api/v4 ${CI_PROJECT_PATH}
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: always
        - changes:
              - renovate.json
